server.port = 8070

#Database
spring.datasource.url = jdbc:postgresql://uvgoserver.postgres.database.azure.com:5432/uvgodatabase
spring.datasource.username = david
spring.datasource.password = david123
