CREATE TABLE kits (
    id_kit INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    curso VARCHAR(150) NOT NULL,
    precio NUMERIC(10,2) NOT NULL CHECK (precio >= 0),
    estado BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO kits (nombre, descripcion, curso, precio, estado) VALUES
    ('Kit de Química General', 'Bata, lentes de seguridad y guantes de nitrilo', 'Química General', 185.00, TRUE),
    ('Kit de Dibujo Técnico', 'Escuadras, compás, portaminas y borrador', 'Dibujo Técnico', 120.50, TRUE),
    ('Kit de Electrónica Básica', 'Protoboard, resistencias, LEDs y cables jumper', 'Física 2', 210.00, TRUE);
