ALTER TABLE kits ADD COLUMN kit_base_id INTEGER REFERENCES kits(id_kit);
ALTER TABLE kits ADD COLUMN estado_personalizacion VARCHAR(20) NOT NULL DEFAULT 'BASE'
    CHECK (estado_personalizacion IN ('BASE', 'PERSONALIZADO'));

CREATE TABLE articulos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kit_id INTEGER NOT NULL REFERENCES kits(id_kit),
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    cantidad NUMERIC(12,3) NOT NULL CHECK (cantidad > 0),
    categoria VARCHAR(100),
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    observaciones_cotizacion VARCHAR(2000)
);
CREATE INDEX idx_articulos_kit ON articulos(kit_id);
CREATE INDEX idx_kits_base ON kits(kit_base_id);
